version: "3"
services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel
        restart: always
        networks:
            - server
        ports:
            - 80:8000
        links:
            - couchdb
        depends_on:
            - couchdb

    couchdb:
        image: couchdb:3.3.2
        container_name: couchdb
        restart: always
        ports:
            - 404:5984
        volumes:
            - couchdb:/opt/couchdb/
        networks:
            - server
        environment:
            COUCHDB_USER: admin
            COUCHDB_PASSWORD: admin

networks:
    server:

volumes:
    couchdb:
